(cl:defpackage jaguar4x4_2014-msg
  (:use )
  (:export
   "<GPSINFO>"
   "GPSINFO"
   "<IMUDATA>"
   "IMUDATA"
   "<MOTORBOARDINFO>"
   "MOTORBOARDINFO"
   "<MOTORBOARDINFOARRAY>"
   "MOTORBOARDINFOARRAY"
   "<MOTORDATA>"
   "MOTORDATA"
   "<MOTORDATAARRAY>"
   "MOTORDATAARRAY"
  ))

