#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/jojo/master1_ws/devel_isolated/orb_slam2_ros:/home/jojo/master1_ws/devel_isolated/jaguar4x4_2014:/home/jojo/master1_ws/devel_isolated/hokuyo_node:/home/jojo/master1_ws/devel_isolated/hector_trajectory_server:/home/jojo/master1_ws/devel_isolated/hector_slam_launch:/home/jojo/master1_ws/devel_isolated/hector_slam:/home/jojo/master1_ws/devel_isolated/hector_map_server:/home/jojo/master1_ws/devel_isolated/hector_geotiff_plugins:/home/jojo/master1_ws/devel_isolated/hector_geotiff:/home/jojo/master1_ws/devel_isolated/hector_nav_msgs:/home/jojo/master1_ws/devel_isolated/hector_marker_drawing:/home/jojo/master1_ws/devel_isolated/hector_mapping:/home/jojo/master1_ws/devel_isolated/hector_compressed_map_transport:/home/jojo/master1_ws/devel_isolated/hector_map_tools:/home/jojo/master1_ws/devel_isolated/hector_imu_tools:/home/jojo/master1_ws/devel_isolated/hector_imu_attitude_to_tf:/home/jojo/master1_ws/devel_isolated/hector_geotiff_launch:/home/jojo/master1_ws/devel_isolated/driver_common:/home/jojo/master1_ws/devel_isolated/driver_base:/home/jojo/orb_ws/devel:/opt/ros/noetic:/home/jojo/master1_ws/devel_isolated/librealsense2:/usr/local'
export LD_LIBRARY_PATH='/home/jojo/master1_ws/devel_isolated/jaguar4x4_2014/lib:/home/jojo/master1_ws/devel_isolated/hokuyo_node/lib:/home/jojo/master1_ws/devel_isolated/hector_trajectory_server/lib:/home/jojo/master1_ws/devel_isolated/hector_slam_launch/lib:/home/jojo/master1_ws/devel_isolated/hector_map_server/lib:/home/jojo/master1_ws/devel_isolated/hector_geotiff_plugins/lib:/home/jojo/master1_ws/devel_isolated/hector_geotiff/lib:/home/jojo/master1_ws/devel_isolated/hector_nav_msgs/lib:/home/jojo/master1_ws/devel_isolated/hector_marker_drawing/lib:/home/jojo/master1_ws/devel_isolated/hector_mapping/lib:/home/jojo/master1_ws/devel_isolated/hector_compressed_map_transport/lib:/home/jojo/master1_ws/devel_isolated/hector_map_tools/lib:/home/jojo/master1_ws/devel_isolated/hector_imu_tools/lib:/home/jojo/master1_ws/devel_isolated/hector_imu_attitude_to_tf/lib:/home/jojo/master1_ws/devel_isolated/hector_geotiff_launch/lib:/home/jojo/master1_ws/devel_isolated/driver_base/lib:/home/jojo/orb_ws/devel/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/aarch64-linux-gnu:/home/jojo/master1_ws/devel_isolated/librealsense2/lib:/home/jojo/master1_ws/devel_isolated/librealsense2/lib/aarch64-linux-gnu:/usr/local/lib'
export PATH='/opt/ros/noetic/bin:/home/jojo/master1_ws/devel_isolated/librealsense2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/jojo/master1_ws/devel_isolated/jaguar4x4_2014/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hokuyo_node/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_trajectory_server/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_slam_launch/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_map_server/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_geotiff_plugins/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_geotiff/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_nav_msgs/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_marker_drawing/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_mapping/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_compressed_map_transport/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_map_tools/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_imu_tools/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_imu_attitude_to_tf/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/hector_geotiff_launch/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/driver_base/lib/pkgconfig:/home/jojo/orb_ws/devel/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/opt/ros/noetic/lib/aarch64-linux-gnu/pkgconfig:/home/jojo/master1_ws/devel_isolated/librealsense2/lib/pkgconfig:/home/jojo/master1_ws/devel_isolated/librealsense2/lib/aarch64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig'
export PYTHONPATH='/home/jojo/master1_ws/devel_isolated/jaguar4x4_2014/lib/python3/dist-packages:/home/jojo/master1_ws/devel_isolated/hokuyo_node/lib/python3/dist-packages:/home/jojo/master1_ws/devel_isolated/hector_nav_msgs/lib/python3/dist-packages:/home/jojo/master1_ws/devel_isolated/hector_mapping/lib/python3/dist-packages:/home/jojo/master1_ws/devel_isolated/driver_base/lib/python3/dist-packages:/home/jojo/orb_ws/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/home/jojo/master1_ws/devel_isolated/librealsense2/lib/python3/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/jojo/master1_ws/devel_isolated/orb_slam2_ros/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/jojo/master1_ws/src/orb_slam_2_ros:$ROS_PACKAGE_PATH"